spring:
  application:
    name: tbill-backend-api

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://${DB_POSTGRES_HOST}:${DB_POSTGRES_PORT}/${DB_POSTGRES_DBNAME}
    username: ${DB_POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # MySQL
  secondary-datasource:
    mysql:
      url: jdbc:mysql://${DB_MYSQL_HOST}:${DB_MYSQL_PORT}/${DB_MYSQL_DBNAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ${DB_MYSQL_USER}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# k8s Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true