spring:
  application:
    name: tbill-backend-api
  
  # ======== 기본 프로필 지정 ========
  # K8s 환경변수(SPRING_PROFILES_ACTIVE)가 없으면 'local'을 기본값으로 사용
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

# k8s Actuator (모든 환경에서 공통으로 노출)
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"