apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # PostgreSQL 접속 정보
  DB_POSTGRES_HOST: "postgres-svc"
  DB_POSTGRES_PORT: "5432"
  DB_POSTGRES_DBNAME: "postgres" # 사용할 DB 이름
  DB_POSTGRES_USER: "postgres" # 기본 관리자 유저

  # MySQL 접속 정보
  DB_MYSQL_HOST: "mysql-svc"
  DB_MYSQL_PORT: "3306"
  DB_MYSQL_DBNAME: "mysql" # 사용할 DB 이름
  DB_MYSQL_USER: "root" # 기본 관리자 유저