apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    # (중요) Nginx Ingress가 경로를 재작성하도록 설정
    nginx.ingress.kubernetes.io/rewrite-target: /$2 
spec:
  ingressClassName: nginx # 2단계에서 설치한 nginx Ingress 사용
  rules:
    - host: localhost # localhost 주소로 접속
      http:
        paths:
          # (중요) /api/java/ 로 시작하는 모든 요청
          - path: /api/java(/|$)(.*)
            pathType: ImplementationSpecific # <-- Prefix에서 변경
            backend:
              service:
                name: backend-java-svc # Java Service로 라우팅
                port:
                  number: 8080

          # (중요) /api/python/ 로 시작하는 모든 요청
          - path: /api/python(/|$)(.*)
            pathType: ImplementationSpecific # <-- Prefix에서 변경
            backend:
              service:
                name: backend-python-svc # Python Service로 라우팅
                port:
                  number: 8000

          # 그 외의 모든 요청 ( / )
          - path: /()(.*)
            pathType: ImplementationSpecific # <-- Prefix에서 변경
            backend:
              service:
                name: frontend-svc # Frontend Service로 라우팅
                port:
                  number: 80